### ISSUE TITLE
Feature request: Widescreen mode

### ISSUE THREAD

**Issue by dariusz-wozniak** [rowrawer/lastfm-debloater#1]
Hi! Thanks for the debloater - I am actively using this and makes me feel better :)

One feature that would be nice to have is to have option for widescreen support, so the "Recent Tracks" are wider.

One of the option would be to change:
- `.container` width to `fit-content`
- `.col-main` width to `1600px`

Thanks :)

**Comment by 54ac** [comment]
Hi, thanks for your kind words :)

Good idea, for some reason I haven't thought of that. I'll get on it.

**Comment by 54ac** [comment]
"Fit main column to page width" option is now available in v1.5.1. Let me know if it works properly for you.

**Comment by dariusz-wozniak** [comment]
Wow, that was super quick. It works great now, thanks!!
